# Fichier de log
LogFile=C:\Program Files\Zabbix Agent\zabbix_agentd.log
LogFileSize=10

### Connexion au serveur Zabbix
Server=172.31.37.37

# Utilisé pour les "Active checks"
ServerActive=172.31.37.37

### Identification du PC
Hostname=Fennan-Client-Windows

### Paramètres de performance
ListenPort=10050
BufferSend=5
BufferSize=100